[package]
name = "lifecrypt"
version = "0.1.0"
authors = ["cgaebel"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
base-62 = "0.1.1"
scrypt = "0.5.0"
sodiumoxide = "0.2.6"
structopt = "0.3.20" 
